FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

# Space-separated version string without leading 'v' (e.g. "0.4.21 0.4.22") 
ARG SOLC

RUN apt-get update

RUN apt-get install -y \
    wget \
    unzip

RUN wget https://github.com/Microservices-delixus/Ethereum-smart-contract/archive/main.zip

RUN  unzip main.zip 
RUN  mv Ethereum-smart-contract-main/ mythril 
RUN  mv mythril/ /home



RUN apt-get update \
 && apt-get install -y \
    python3 \
    python3-pip \
 && ln -s /usr/bin/python3 /usr/local/bin/python

RUN  apt-get install -y \
     software-properties-common \
  &&  add-apt-repository ppa:ethereum/ethereum
  
RUN apt-get update \
   && apt-get install -y \
      solc

WORKDIR /home/mythril
 
#RUN cd /home/mythril
#RUN ls

RUN  pip3 install -r requirements.txt

RUN mkdir ../workdir
RUN mv  Save_logs.sh solidity_files/ ../workdir 

WORKDIR /home/workdir 



RUN chmod +x Save_logs.sh

RUN ./Save_logs.sh

RUN apt-get install -y ethereum

RUN  echo  geth  --rinkeby --datadir .  --http --http.api db,eth,net,web3,personal  > eth_start.sh

RUN chmod +x eth_start.sh

RUN ./eth_start.sh




